apiVersion: v1
kind: ConfigMap
metadata:
  name: additional-scrape-configs
  namespace: monitoring
data:
  additional-scrape-configs.yaml: |
    - job_name: 'flask-app'
      metrics_path: /metrics
      static_configs:
        - targets: ['192.168.49.2:30017']
