version: 0.2

phases:
  pre_build:
    commands:
      - echo "Setting up kubeconfig..."
      - aws eks update-kubeconfig --region us-east-1 --name my-cluster

  build:
    commands:
      - echo "Fetching service details from EKS..."
      - SERVICE_NAME="hello-springboot-app-service"
      - NODE_PORT=$(kubectl get svc $SERVICE_NAME -o jsonpath='{.spec.ports[0].nodePort}')
      - NODE_IP=$(kubectl get nodes -o jsonpath='{.items[0].status.addresses[?(@.type=="ExternalIP")].address}')
      - APP_URL="http://$NODE_IP:$NODE_PORT"
      - echo App URL: "$APP_URL"



