version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - export IMAGE_TAG
      - echo "IMAGE_TAG=$IMAGE_TAG"

  build:
    commands:
      - echo Building the Maven project..
      - mvn clean package
      - echo Building the Docker image...
      - docker build -t rajkashyap12/hello-springboot-app:$IMAGE_TAG -f Jenkins_Assignment_7/hello-springboot-app/Dockerfile Jenkins_Assignment_7/hello-springboot-app
      - docker push rajkashyap12/hello-springboot-app:$IMAGE_TAG

  post_build:
    commands:
      - echo Updating deployment.yaml with new image...
      - sed -i 's|image:.*|image: rajkashyap12/hello-springboot-app:'"$IMAGE_TAG"'|g' Jenkins_Assignment_7/hello-springboot-app/deployment.yaml
      - echo Applying Kubernetes manifests to EKS...
      - aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME
      - kubectl apply -f Jenkins_Assignment_7/hello-springboot-app/deployment.yaml


artifacts:
  files:
    - deployment.yaml
