---
- name: Linux server setup
  hosts: server
  become: true

  roles:
    - linux_patching
    - tomcat_install
    - dns_changes

- name: Windows IIS_setup
  hosts: win_server
  roles:
    - win_iis