apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  ports:
  - port: 3306      # MySQL default port
    targetPort: 3306
  selector:
    app: mysql       # Matches the label from the MySQL Deployment
