pipeline {
    agent any

    environment {
        SONAR_SCANNER_HOME = tool 'Sonar_5'  // Ensure this tool is configured
    }

    stages {
        stage('Setup Python Virtual Env') {
            steps {
                dir('python_sonar_jenkins_project') {
                sh '''
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install --upgrade pip
                    pip install pytest coverage
                '''
            }
        }
        }
        stage('Run Tests and Generate Coverage') {
            steps {
                dir('python_sonar_jenkins_project') {
                // Activate the virtual environment and run tests with coverage
                sh '''
                    . venv/bin/activate
                    coverage erase
                    coverage run -m pytest -p no:ddtrace
                    coverage report
                    coverage xml
                    
                '''
            }
        }
        }
        stage('SonarQube Analysis') {
            steps {
                dir('python_sonar_jenkins_project') {
                    withSonarQubeEnv('Sonar_Local') {
                        sh '''
                        . venv/bin/activate
                        ${SONAR_SCANNER_HOME}/bin/sonar-scanner
                        '''
            }
        }
    }
}
}
}