pipeline {
    agent any

    environment {
        SONAR_SCANNER_HOME = tool 'SonarScanner'  // Ensure this tool is configured
    }

    stages {
        stage('Setup Python Virtual Env') {
            steps {
                sh '''
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install --upgrade pip
                    pip install pytest coverage
                '''
            }
        }

        stage('Run Tests and Generate Coverage') {
            steps {
                sh '''
                    . venv/bin/activate
                    coverage erase
                    coverage run -m pytest
                    coverage xml
                    sed -i 's|<source>.*</source>|<source>.</source>|g' coverage.xml
                '''
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('MyLocalSonar') {
                    sh '''
                        . venv/bin/activate
                        ${SONAR_SCANNER_HOME}/bin/sonar-scanner
                    '''
                }
            }
        }
    }
}
