pipeline {
    agent any

    environment {
        IMAGE_NAME = 'rajkashyap12/flask-cicd-app'
        CREDENTIALS_ID = 'dockerhub'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("${IMAGE_NAME}:latest","Jenkins-Docker")
                }
            }
        }

        stage('Push to DockerHub') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', CREDENTIALS_ID) {
                        docker.image("${IMAGE_NAME}:latest").push()
                    }
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                script {
                    // Stop previous container if running (Linux sh commands)
                    sh '''
                        docker stop flask-app || true
                        docker rm flask-app || true
                        docker run -d -p 5000:5000 --name flask-app rajkashyap12/flask-cicd-app:latest
                    '''
                }
            }
        }
    }
}
