apiVersion: apps/v1
kind: Deployment
metadata:
  name: registration-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registration
  template:
    metadata:
      labels:
        app: registration
    spec:
      containers:
      - name: registration-container
        image: registration-app:latest
        ports:
        - containerPort: 8080
