// Jenkinsfile for hello-springboot-app
pipeline {
    agent {label "slave-node"}
    environment {
        DOCKERHUB_CREDENTIALS = credentials('rajkashyap12')
    }
    stages {
        stage('SCM Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Raj123-dev/Devops_Journey_2k25.git'
            }
        }
        stage('Build JAR') {
            steps {
                dir('Jenkins_Assignment_7/hello-springboot-app') {
                    sh 'mvn clean package'
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                dir('Jenkins_Assignment_7/hello-springboot-app') {
                    sh 'sudo docker build -t rajkashyap12/master-slave:hello-springboot-app_$BUILD_NUMBER .'
                }
            }
        }
        stage('Login to DockerHub') {
            steps {
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | sudo docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
            }
        }
        stage('Push Image') {
            steps {
                dir('Jenkins_Assignment_7/hello-springboot-app') {
                    sh 'sudo docker push rajkashyap12/master-slave:hello-springboot-app_$BUILD_NUMBER'
                }
            }
        }
    }
    post {
        always {
            sh 'sudo docker logout'
        }
    }
}
